### ISSUE TITLE
Modify sidebar beyond config.toml

### ISSUE THREAD

**Issue by andrewrgoss** [enten/hyde-y#14]
If I wanted to modify the sidebar to include a logo image and and tweak the container title div to be `h2-like` - which theme file(s) would I change so that the html files generated by Hugo all reflect this? Don't want to have to modify each of the index.html files.

```
  <main id="main-wrapper" class="container main_wrapper has-sidebar">
    <header id="main-header" class="container main_header">
  <div class="container brand">
  <div class="container title h1-like">
  <a class="baselink" href="http://localhost:1313/">
  Andrew Goss
</a>
</div>
<div class="container topline">
  Data Engineer and Business Intelligence Developer
</div>
</div>
  <nav class="container nav primary no-print">
<a class="homelink" href="http://localhost:1313/">Home</a>
<a href="http://localhost:1313/about">About</a>
<a href="http://localhost:1313/post" title="Show list of posts">Posts</a>
<a href="http://localhost:1313/tags" title="Show list of tags">Tags</a>
<a href="http://localhost:1313/learning">Learning</a>
</nav>
<div class="container nav secondary no-print">
<a id="contact-link-email" class="contact_link" href="mailto:andrewrgoss@gmail.com">
  <span class="fa fa-envelope-square fa-2x"></span><span>email</span></a>
<a id="contact-link-github" class="contact_link" href="https://github.com/andrewrgoss">
  <span class="fa fa-github-square fa-2x"></span><span>github</span></a>
<a id="contact-link-linkedin" class="contact_link" href="https://www.linkedin.com/in/andrewrgoss">
  <span class="fa fa-linkedin-square fa-2x"></span><span>linkedin</span></a>
<a id="contact-link-twitter" class="contact_link" href="https://twitter.com/andrewrgoss">
  <span class="fa fa-twitter-square fa-2x"></span><span>twitter</span></a>
</div>
</header>
```

**Comment by enten** [comment]
> I wanted to modify the sidebar to include a logo image 

Into your `config.toml`, you can use markdown in the `brand` variable (and `topline`/`footline` too): use it to include your brand logo.

> I wanted to tweak the container title div to be h2-like

The simplest way is to override [`layouts/partials/bloc/header/brand_title.html`](https://github.com/enten/hyde-y/blob/master/layouts/partials/bloc/header/brand_title.html):
- cd into your project folder
- create `layouts/partials/bloc/header/brand_title.html` file
- and paste the folowing code:

``` html
<div class="container title h2-like">
  {{ partial "modules/site/link/base" . }}
</div>
```

Hyde-Y is highly customizable: every layout blocks are pieces of HTML code individually stored. So you can override every piece of the interface easily.

**Comment by andrewrgoss** [comment]
Thank you, exactly the information I needed. Appreciate the timely response.

**Comment by enten** [comment]
You're welcome
