### ISSUE TITLE
Default ListPage View?

### ISSUE THREAD

**Issue by bradysalz** [enten/hyde-y#27]
Hey there,

If I take the template and add a new item to `Menu.toml`:

```
[portfolio]
	Name = "portfolio"
	Title = "Projects I've done"
	URL = "/portfolio"
```
Then make a new test page using `hugo new portfolio/first_project.md`. This is currently saved as a draft. To see if things are working, I run the local server and check if `/portfolio/` loads. It doesn't, and 404's. If I change my first post from draft to finished, everything works as expected.

Is this intended? I assumed the correct behavior would be to just present an empty ListPage with no entries (I believe Taxonomies do this currently).

**Comment by enten** [comment]
I haven't used Hugo for a long time.
But I think that behavior depends from Hugo.

**Comment by bradysalz** [comment]
It's fine either way really, was just curious. Hopefully just logging this will help some other people who got stuck in a silly rut like me.
