### ISSUE TITLE
Fixed landing page?

### ISSUE THREAD

**Issue by jbkoh** [enten/hyde-y#33]
Hi, thanks for sharing the great effort.

Can I show a fixed landing page instead of showing paginations?

Thank you.

**Comment by enten** [comment]
Yes, you can.

You only need to edit the "homepage" partial ([layouts/partials/homepage.html](https://github.com/enten/hyde-y/blob/master/layouts/partials/homepage.html)).

**Comment by TheDcoder** [comment]
I have [replied](https://github.com/enten/hyde-y/issues/19#issuecomment-289268708) to a similar question #19, you might want to check it out 😉

**Comment by jbkoh** [comment]
Thank you all very much. I am closing this issue.
