### ISSUE TITLE
Pagination does not appear to be working. 

### ISSUE THREAD

**Issue by jsilve24** [enten/hyde-y#34]
First off, thank you for creating this theme!

I am having a problem with Pagination. 
I now have 11 posts on my site: https://github.com/jsilve24/stats_at_home (http://statsathome.com) and I was introduced to the pagination feature which defaults to 10. This is great however clicking on the link to the second page leads to an invalid URL (http://page/2/). I am not sure how to fix this but help would be greatly appreciated!

I am not sure if there is other information I should be providing, it seems like it should be a simple fix...

Thank you,
Justin

**Comment by enten** [comment]
**Have you clone [enten/hugo-boilerplate](https://github.com/enten/hugo-boilerplate/) to initialize your hugo's project?**

**How you named your base url variable in the `config.toml`?**

In [modules/site/pagination.html#L1](https://github.com/enten/hyde-y/blob/86e75dd13320a23ceb3012c36d760044a77f0157/layouts/partials/modules/site/pagination.html#L1) we defines `{{ $baseurl := .Site.BaseURL }}`.

So, I think there is a mistake with the name `baseurl` in the `config.toml`: the name may be `baseURL`. I made that mistake in [enten/hugo-boilerplate/config.toml#L2](https://github.com/enten/hugo-boilerplate/blob/de664ab3e855650a50e816f7ae603d083f8310a2/config.toml#L2) too.

**Comment by jsilve24** [comment]
Here is the first few lines of my config.toml. I added both baseurl definition and BaseURL definition as I did not completely understand you last comment. I am still having the same issue... 

```
# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://www.statsathome.com/"
BaseURL = "http://www.statsathome.com/"
```

**Comment by jsilve24** [comment]
using "baseURL" also does not fix the problem

**Comment by enten** [comment]
Which version of hugo do you use?

I made a test a few minutes ago and I can't reproduce this issue. I'm using hugo v0.15.

```shell
$ hugo version
Hugo Static Site Generator v0.15 BuildDate: 2015-11-25T15:35:21+01:00
```

![screenshot](http://i.imgur.com/ILMc5LP.png)

**Comment by jsilve24** [comment]
Hugo Static Site Generator v0.20.2 darwin/amd64 BuildDate: 2017-04-16T11:02:29-04:00

**Comment by jsilve24** [comment]
you can just download my site from 

https://github.com/jsilve24/stats_at_home <https://github.com/jsilve24/stats_at_home>

and set paginate to 10, you should see the problem. 

Justin

**Comment by enten** [comment]
I still can't reproduce this issue with the v0.15.

I quickly check hugo's documentation and it seem there is not breaking change with `.Site.BaseURL`.

![screenshot](http://i.imgur.com/cRPbd2L.png)

**Comment by jsilve24** [comment]
I have been also discussing this issue no the Hugo forum. someone there seems to have figured out part of the issue with the theme. 

https://discourse.gohugo.io/t/question-about-pagination-problem-with-hyde-y-theme/7919/4 <https://discourse.gohugo.io/t/question-about-pagination-problem-with-hyde-y-theme/7919/4>

**Comment by enten** [comment]
Wonderful!

I seen that pagination's section doesn't exists in the documentation until February 2017.

So this issue is due to the hugo's version.

Below a fix provided by @bep 

> Create a file in your local project
> 
> `/layouts/partials/modules/site/pagination.html`
> 
> With this content:
> 
> ```html
> {{ template "_internal/pagination.html" . }}
> ```

**Comment by jsilve24** [comment]
Yes... but as I then followed up with. There is still a problem. Unfortunately, the pagination buttons are coming up as bullet points…


![](https://cdn-standard5.discourse.org/uploads/gohugo/original/2X/e/ef97f47c10cd575c3d4f2337fb8c58bb841800cb.png)

**Comment by enten** [comment]
```shell
$ cd stats_at_home
$ cd themes/hyde-y
$ nano scss/_04-themes.less
$ # add the code below and save changes
$ npm install
$ npm run build:css
$ cd ../..
$ hugo server -w -D
```

```less
/** stats_at_home/themes/hyde-y/scss/_04-themes.less */

.main_wrapper {
  /** vvv Add lines below */
  ul.pagination {
    list-style-type: none;
  }

  ul.pagination > li {
    display: inline;
  }
  /** ^^^ Add lines above */

  &> .main_header {
    /** ... */
  }
}
```

**Comment by jsilve24** [comment]
Awesome!!! That totally fixed the problem! Thank you!
