### ISSUE TITLE
change bar color

### ISSUE THREAD

**Issue by patarol** [enten/hyde-y#39]
I'm a ` R / Python` programmer and I have difficult to understand some codes in `.js` or `.css`... 

I'm trying to change the bar color (#2053AB)  in my `hyde-y` website and I can't do it... I've tried to follow the steps from the 'README.md´ and nothing happens...

How can I change it?

Any help is appreciated.

**Comment by enten** [comment]
I just tried:

1. set `@primary-background: red;` into [scss/_00-config.less#46](https://github.com/enten/hyde-y/blob/a80eb4a3fd11878ba5bdb3a2ab7167eb12aa50af/scss/_00-config.less#L46) ;
2. run `npm install && npm run build:css` ;
3. done!

After that, [static/css/styles.css](https://github.com/enten/hyde-y/blob/master/static/css/style.css) will be update with your color change.

Do you have a public repository? I that case, I will check why you didn't succeed to update the stylesheet.

**Comment by patarol** [comment]
Thank you @enten!

It worked!!! 

I assume that I can use the same method to edit font family and color, right?!

Thank you again!!

**Comment by enten** [comment]
> I assume that I can use the same method to edit font family and color, right?!

Yes, it is the same method :+1:
