### ISSUE TITLE
Increase size of social icons

### ISSUE THREAD

**Issue by cpraveen** [enten/hyde-y#4]
Hello
How to increase the size of icons that are used for twitter, github, etc.
Thanks

**Comment by enten** [comment]
FA ([Font Awesome](https://fortawesome.github.io/Font-Awesome)) are used for the icons.

Icons are unicode characters. You can increase their sizes with CSS.

Another way is to add CSS classes from FA as these [examples](https://fortawesome.github.io/Font-Awesome/examples/) (section "Larger Icons") to each social links which are stored under [themes/hyde-y/layouts/partials/modules/links/social/](https://github.com/enten/hyde-y/tree/master/layouts/partials/modules/site/link/social).

**Example with Facebook social link**

``` html
{{ with .Site.Params.facebook }}
<a id="contact-link-facebook" class="contact_link" href="https://www.facebook.com/{{ . }}">
  <span class="fa fa-facebook-square fa-2x"></span><span>facebook</span></a>
{{ end }}
```

In the example above, I added the FA CSS class "fa-2x" to let FA rules increase the icon size of Facebook link.

**Comment by cpraveen** [comment]
Thank you very much.

**Comment by dmial** [comment]
Hi.

Could you please answer: how can I add this new icon to the theme: https://fontawesome.com/icons/telegram?style=brands

I've tried your second approach with changing of font-awesome.min.css  to a [new versio](https://use.fontawesome.com/releases/v5.5.0/css/all.css)n. But nothing helps.
