### ISSUE TITLE
cannot run local server

### ISSUE THREAD

**Issue by vanhumbeecka** [enten/hyde-y#42]
Somehow, running ```hugo server -D``` with this template returns te following...

```
Building sites … ERROR 2018/09/17 21:17:18 Error while rendering "section" in "": template: _default/section.html:6:29: executing "_default/section.html" at <.Paginator.Pages>: undefined variable: $index
```

**Comment by enten** [comment]
I reproduce that error with hugo 0.48.

The source of this issue I seems to be `RSSLink`.

I made [a commit to remove use of RSSLink](https://github.com/enten/hyde-y/commit/b72df4f2130f595b21f8a45d0b31654c25f130b4).

This issue need to be investigated to understand why RSSLink doesn't works anymore.
