### ISSUE TITLE
How can I change the main font?

### ISSUE THREAD

**Issue by glacjay** [enten/hyde-y#5]
I want to change the font's family or size.

**Comment by enten** [comment]
In your project folder, creates file **layouts/partials/head-extra.html** and writes your font imports and your custom CSS.

That file will be included before the end tag `</head>`.

**Example of content for your head-extra.html**

``` html
<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<style>
body {
  font-family: 'Open Sans';
}
</style>
```

**Comment by glacjay** [comment]
Thanks, it works.
